# -*- coding: utf-8 -*-
"""Mini_Projects

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SBt2FzxPW9w5Suxz5ziEU9w564iXe4sl

**# MINI PROJECT 1**
## Tanvir Alam
### January 11, 2021
#### This project uses input from the user to calculate if the integers are even or odd
"""

print("sums of odd and even numbers")
print()

#user input
#First test: failure!
num = int(input("Enter this interger: "))
#made a list combined with user input
numbers = list(range(1, 11))
print(numbers)
numbers = list(range(10, 21, 2))
print(numbers)
numbers = list(range(20, 31, 1))
print(numbers)
#created conditions
if int(num) % 2 == 0:
  print('The number you input is an even')
else:
  print('The number you input is an odd')

# user_input
##second test: success!
num = int(input("Please enter a number: "))
print(num)
if (num % 2) == 0:
  print('The number you input is an even')
if (num % 2) > 0:
  print('The number you input is an odd')

#BONUS
#checking if the number is a multiple of 4
num = int(input("Enter a number: "))

if num % 4 == 0:
    print("I am a multiple of 4")
if num % 4 != 0:
  print("I am not a multiple of 4")

#ask the user for two numbers
num_1 = int(input("Enter the first number: "))
check = int(input("Enter the second number: "))

if num % check == 0:
  print('The first number can be divided by the second number')
else: 
  print('the first number cannnot be divided by the second number')

# A custom function: MAIN PROGRAM
num_1 = int(input("Enter the first number: "))
check = int(input("Enter the second number: "))
#added greeting to introduce the fuctions
def greeting(num_1 = 10, check = 2):
  """This will display if the interger even or odd"""
print('the even number is: ', + num_1 )
print('this is not a odd number: ', + check)

greeting()

